import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { NavLinks } from '@/components/nav/nav-links'


export const metadata: Metadata = {
  title: "UniProject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavLinks />
        <div id="__next">
        </div>
        {children}
        <script src="https://kit.fontawesome.com/4b77a64568.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}